--FACE FROM : https://create.roblox.com/store/asset/6746344777/Classic-Roblox-Facepack
-- '{0 or out of range search query}' in the slot for emptying the decal,  '{numbers here}' for decals in sequence/search via texture ID, '{name/content}' to search name and TextureID 

-- EYES
Eyes = {
	a = "http://www.roblox.com/asset/?id=6456031314", -- eyes
	b = "rbxassetid://121977835426000", -- :-/ eyes
	at = "rbxassetid://133742110941586", -- @ @ eyes
	aaaa = "rbxassetid://113135875693956", -- aaaa
	angst = "rbxassetid://106823656228287", -- Angst
	awesome = "rbxassetid://113011182713326", -- awesome eyes
	awkward = "rbxassetid://94602514427529", -- awkward eyes
	biggerdots = "http://www.roblox.com/asset/?id=7155820055", -- biggerdots
	blerg = "rbxassetid://137185608507645", -- blerg eyes
	bubbly = "rbxassetid://84967038835741", -- bubbly eyes
	cautious = "rbxassetid://71330385063147", -- cautious eyes
	chub = "http://www.roblox.com/asset/?id=9868662128", -- chub eyes
	closed = "rbxassetid://110134295377009", -- closed eyes
	dead = "rbxassetid://117891065690999", -- dead
	dilated = "http://www.roblox.com/asset/?id=9868555570", -- dilatedeyes
	dotty = "http://www.roblox.com/asset/?id=9868297420", -- dotty
	eeee = "rbxassetid://137950197761421", -- eeee
	eeee2 = "http://www.roblox.com/asset/?id=9868768590", -- eeee2
	eeee3 = "rbxassetid://126354131956368", -- eeee3
	epic = "rbxassetid://88212621224494", -- epic eyes
	equalsign = "http://www.roblox.com/asset/?id=9869067119", -- equalsign
	fearless = "rbxassetid://117213959891438", -- fearless eyes
	frisk = "http://www.roblox.com/asset/?id=7246617116", -- frisk face -_- <-- OMG Is THAT AN UNDERTALE REFERENCE!!!!?
	ghostface = "rbxassetid://74134091469471", -- ghostface eyes
	giggly = "rbxassetid://124728074153027", -- giggly eyes
	happi = "rbxassetid://123740764230900", -- happi
	happy = "http://www.roblox.com/asset/?id=7155826301", -- happyeyes
	happy2 = "http://www.roblox.com/asset/?id=6746311666", -- happyeyes
	huthut = "rbxassetid://113121586285915", -- huthut eyes
	o = "rbxassetid://101778906454309", -- O-O eyes
	pixel = "rbxassetid://9868984380", -- pixel eyes
	sans = "rbxassetid://123004969170026", -- sans
	shocked = "rbxassetid://130458747784368", -- shocked eyes
	sneaky = "rbxassetid://123663494132447", -- sneaky eyes
	sneakier = "rbxassetid://84418929024906", -- sneaky
	sneaky_flipped = "rbxassetid://136664980692352", -- sneaky flipped
	sonimcri = "rbxassetid://107391790674297", -- sonimcri
	tired = "http://www.roblox.com/asset/?id=7155823474", -- tired
	tired2 = "rbxassetid://6943703055", -- tired
	ugh = "rbxassetid://71330385063147", -- ugh
	ugh_flipped = "rbxassetid://87307329575784", -- ugh flipped
	watchoo = "rbxassetid://76225156674551", -- watchoo eyes
	watchoo2 = "rbxassetid://76225156674551", -- watchoo
	watchooflipped = "rbxassetid://122672772095415", -- watchooflipped
	wink = "rbxassetid://73303288011834", -- wink eyes
	wink2_left = "rbxassetid://113861739642578", -- wink2 left
	wink2_right = "rbxassetid://73303288011834", -- wink2 right
	wink_left = "rbxassetid://105395407503064", -- wink left
	wink_right = "rbxassetid://111720047725986", -- wink right
	x = "http://www.roblox.com/asset/?id=9868461640", -- x
}

-- MOUTHS
Mouths = {
	at = "rbxassetid://82144014369948", -- @ @ mouth
	mm = "rbxassetid://99122751715720", -- :-/ mouth
	aaaaa = "rbxassetid://120009486489139", -- aaaaa
	awesome = "rbxassetid://126483932561159", -- awesome mouth
	awkward = "http://www.roblox.com/asset/?id=10425882204", -- awkward mouth
	aww = "http://www.roblox.com/asset/?id=9868488747", -- aww
	blerg = "rbxassetid://80114321191768", -- blerg mouth
	bubbly_smile = "rbxassetid://122552274681923", -- bubbly smile
	cautious = "rbxassetid://76292734719099", -- cautious mouth
	chub_smile = "http://www.roblox.com/asset/?id=9868690643", -- chub smile
	defaultsmile = "rbxassetid://132830547562594", -- defaultsmile
	epic = "rbxassetid://97115826561448", -- epic mouth
	erm = "rbxassetid://118036594001467", -- erm
	erm2 = "rbxassetid://73943224790777", -- erm2
	fearless = "rbxassetid://102882792797404", -- fearless mouth
	ghostface = "rbxassetid://106978916578637", -- ghostface mouth
	giggly = "rbxassetid://130280495197673", -- giggly mouth
	happy = "http://www.roblox.com/asset/?id=7155831824", -- happy
	happy2 = "rbxassetid://79076791481319", -- happy2
	happy3 = "http://www.roblox.com/asset/?id=6456031519", -- happy3
	happy4 = "http://www.roblox.com/asset/?id=9868598862", -- happy4
	huthut_nose = "rbxassetid://124234500758049", -- huthut nose + mouth
	neutral = "http://www.roblox.com/asset/?id=9868532598", -- neutral
	neutral4 = "http://www.roblox.com/asset/?id=7155827922", -- neutral
	neutral2 = "http://www.roblox.com/asset/?id=6714616147", -- neutral2
	neutral3 = "rbxassetid://77695278372431", -- O-O mouth
	om = "http://www.roblox.com/asset/?id=9868960571", -- om
	omg2 = "rbxassetid://118584096582466", -- omg2
	p = "http://www.roblox.com/asset/?id=9868283931", -- p
	pixel_smile = "http://www.roblox.com/asset/?id=9869004595", -- pixel smile
	sad = "http://www.roblox.com/asset/?id=7155830121", -- sad
	sad3 = "http://www.roblox.com/asset/?id=6681434876", -- sad
	sad2 = "rbxassetid://107028018818915", -- sad2
	sadder = "rbxassetid://83908679991206", -- sadder
	shocked = "rbxassetid://84406222278762", -- shocked mouth
	smug = "http://www.roblox.com/asset/?id=9868915708", -- smug
	smug2 = "rbxassetid://108072808625272", -- smug2
	sneaky = "rbxassetid://114996737440795", -- sneaky mouth
	uwu = "http://www.roblox.com/asset/?id=9869048800", -- uwu
	veryhappi = "rbxassetid://123362279584903", -- veryhappi
	watchoo = "rbxassetid://130810917014936", -- watchoo mouth
	wiggly = "http://www.roblox.com/asset/?id=6746312030", -- wiggly
	wink_mouth_grin = "rbxassetid://98422123865214", -- wink mouth / grin
	yay = "http://www.roblox.com/asset/?id=9868429559", -- yay
}

-- BROWS
Brows = {
	angry = "http://www.roblox.com/asset/?id=9868703100", -- angry
	dinkbros = "http://www.roblox.com/asset/?id=9868876405", -- dinkbros
	huh = "http://www.roblox.com/asset/?id=9868892272", -- huh
	itsgotime = "http://www.roblox.com/asset/?id=9868753482", -- itsGoTime
	ohwow = "http://www.roblox.com/asset/?id=9868942608", -- ohWow
	onebrowup = "http://www.roblox.com/asset/?id=9868926153", -- onebrowup
	smug = "http://www.roblox.com/asset/?id=9868910668", -- smug
	sneaky = "rbxassetid://106528367953196", -- sir u ain't hiding it lowky
	sneakybrowsflipped = "rbxassetid://86637032840677", -- sneakybrowsflipped
	sorry = "http://www.roblox.com/asset/?id=9868710346", -- sorry
	surprised = "http://www.roblox.com/asset/?id=10425886698", -- surprised
	v = "http://www.roblox.com/asset/?id=9869040463", -- the caret thing rook rook -> ^, and I turn it upside down...... ->>>> v <<<<- WOAH!!!!
	woooah = "http://www.roblox.com/asset/?id=9868520848", -- woooah
}


local TAGEYES = 0
for i,v in Eyes do
	TAGEYES = TAGEYES + 1
end
local TAGMOUTHS = 0
for i,v in Mouths do
	TAGMOUTHS = TAGMOUTHS + 1
end
local TAGBROWS = 0
for i,v in Brows do
	TAGBROWS = TAGBROWS + 1
end
function FFNAC(par, nam, cls)
	if typeof(par) ~= 'Instance' or typeof(nam) ~= 'string' or typeof(cls) ~= 'string' then return end
	for i,v in par:GetChildren() do
		local yes, yesser = pcall(function() return v:IsA(cls) end)
		if v.Name:lower():match(nam:lower()) and ((yes and yesser) or v.ClassName == cls) then
			return v
		end
	end
end
function Apply(Part, a,b,c)
	if typeof(Part) ~= 'Instance' then return end
	if a == 'random' then a = math.random(1, TAGEYES) end if b == 'random' then b = math.random(1, TAGMOUTHS) end if c == 'random' then c = math.random(1, TAGBROWS) end
	if typeof(a) == 'number' then a = tostring(a) end if typeof(b) == 'number' then b = tostring(b) end if typeof(c) == 'number' then c = tostring(c) end
	if a == tostring(tonumber(a)) then
		if tonumber(a) > 100 then
			for i,v in Eyes do
				if tonumber(v) == tonumber(a) then
					a = v
					break
				end
				if i >= TAGEYES then a = nil end
			end
		else 
			local counter = 0
			for i,v in Eyes do
				counter += 1
				if counter == tonumber(a) then
					a = v break
				end
			end
		end
	elseif typeof(a) == 'string' then
		local counter = 0
		for i,v in Eyes do
			counter += 1
			if (i:lower()):match(tostring(a):lower()) or (v:lower()):match(tostring(a):lower()) then
				a = v
				break
			end
			if counter >= TAGEYES then a = nil end
		end
	else a = nil end
	if b == tostring(tonumber(b)) then
		if tonumber(b) > 100 then
			local counter = 0
			for i,v in Mouths do
				counter += 1
				if tonumber(v) == tonumber(b) then
					b = v
					break
				end
				if counter >= TAGMOUTHS then b = nil end
			end
		else 
			local counter = 0
			for i,v in Mouths do
				counter += 1
				if counter == tonumber(b) then
					b = v break
				end
			end
		end
	elseif typeof(b) == 'string' then
		local counted = 0
		for i,v in Mouths do
			counted+=1
			if (i:lower()):match(tostring(b):lower()) or (v:lower()):match(tostring(b):lower()) then
				b = v
				break
			end
			if counted >= TAGMOUTHS then b = nil end
		end 
		else
	b = nil
end 
	if c == tostring(tonumber(c)) then
		if tonumber(c) > 100 then
			local counted = 0
			for i,v in Brows do
				counted+=1
				if tonumber(v) == tonumber(c) then
					c = v
					break
			end
				if counted >= TAGBROWS then c = nil end
			end
		else 
			local counter = 0
			for i,v in Brows do
				counter += 1
				if counter == tonumber(c) then
					c = v break
				end
			end
		end
	elseif typeof(c) == 'string' then
		local counted = 0
		for i,v in Brows do
			counted += 1
			if (i:lower()):match(tostring(c):lower()) or (v:lower()):match(tostring(c):lower()) then
				c = v
				break
			end
		if counted >= TAGBROWS then c = nil end
		end
	else c = nil end
	if typeof(a) == 'string' then
		local EYETXT = FFNAC(Part, 'ASSEMBLE_EYES', 'Decal')
		if not EYETXT then
			EYETXT = Instance.new('Decal', Part) EYETXT.Name = 'ASSEMBLE_EYES' 
		end
		if typeof(EYETXT) == 'Instance' then
			EYETXT.Texture = a or ''
		end
	end
	if typeof(b) == 'string' then
		local EYETXT = FFNAC(Part, 'ASSEMBLE_MOUTHS', 'Decal')
		if not EYETXT then
			EYETXT = Instance.new('Decal', Part) EYETXT.Name = 'ASSEMBLE_MOUTHS' 
		end
		if typeof(EYETXT) == 'Instance' then
			EYETXT.Texture = b or ''
		end
	end
	if typeof(c) == 'string' then
		local EYETXT = FFNAC(Part, 'ASSEMBLE_BROWS', 'Decal')
		if not EYETXT then
			EYETXT = Instance.new('Decal', Part) EYETXT.Name = 'ASSEMBLE_BROWS' 
		end
		if typeof(EYETXT) == 'Instance' then
			EYETXT.Texture = c or ''
		end
	end
end
function ApplyCHR(chr, a,b,c)
	if typeof(chr) ~= 'Instance' then return end
	local head = FFNAC(chr, 'Head', 'BasePart')
	if head then
		local BLOCK = FFNAC(head, 'BLOCK', 'BasePart')
		if BLOCK then head = BLOCK end
	end
	pcall(function()	Apply(head,a,b,c) end) 
end
local Bind = script:FindFirstChildOfClass('BindableEvent')
if not Bind then
	Bind = Instance.new('BindableEvent', script) Bind.Name = 'Event'
end
Bind.Event:Connect(ApplyCHR)